### ISSUE TITLE
Add totalPoints to constructor and engine manufacturer statistics

### ISSUE THREAD

**Issue by marceloverdijk** [f1db/f1db#1]
For driver statistics we currently already differentiating between `totalPoints` and `totalChampionshipPoints`.

E.g. Ayrton Senna has `614` `totalPoints` and `610` `totalChampionshipPoints`.
This due to the fact up until 1990, not all points scored contributed to their final World Championship tally.

Now for `totalPoints` we simply sum all points from the race results and for `totalChampionshipPoints` we sum all points from the driver standings.

For constructors and engine manufacturers we currently only offer the `totalChampionshipPoints` statistics by summing up all points from the constructor standings.

But for constructors and engine manufacturers we don't have a `totalPoints` statistic yet.
Unfortunately it's not a matter of just summing up all points from the race results because:

- Constructors only started scoring points from 1958
- Williams not receiving points in 1995 Brazilian GP, but driver (Coulthard) did
- McLaren excluded from the 2007 championship so no points scored, but drivers did
- ..

To solve this we probably have to add something to the raw race result data. 
E.g. a `constructorPoints` field that could override the `points` field if specified.

**Comment by marceloverdijk** [comment]
Similar we could add a `totalDriverPoints` to the constructor / engine manufacturer statistics.

**Comment by AntonioSchez32** [comment]
There is some info in Stats F1 (https://www.statsf1.com/en/1958.aspx) that would require some web scraping in order to retrieve that information, but I think that is what you are looking for.
