### ISSUE TITLE
Support for Car Name and Engine Info

### ISSUE THREAD

**Issue by enrique-lozano** [f1db/f1db#10]
Hi! It would be really nice to have information about the name of the car model, as well as the engine it mounts (name, engine capacity...). This information is easily extractable from wikipedia or other sources.

However, I don't know how that would affect the current scheme. For example, the same team within a session may have different models:

![image](https://user-images.githubusercontent.com/61509169/203614159-e19800e6-e3eb-43cd-98e4-671e2f6aa92a.png)

For this reason, it would be necessary to introduce information about in which rounds each model participates. In addition, I think it is possible that within the same team and race two drivers participate with a different model.

**Comment by marceloverdijk** [comment]
Yes this would be nice, but honestly I will not look into that with high prio...

Problem is that there is insufficient information available of which chassis (or engine spec in some cases) was used by which driver in which round.
