### ISSUE TITLE
Two issues: bio mix-up and drivers entering races multiple times

### ISSUE THREAD

**Issue by mcnulty4960** [f1db/f1db#23]
Hello! I'm a novice to GitHub, so please forgive any breaches of etiquette.

I have two issues to report, and the first is very simple. To my understanding, in the db-drivers table, the biographical lines of Michael Andretti and Michael Ammermuller are swapped. It reports Andretti as being born in 1986 in Pocking, Germany and Ammermuller being born in 1962 in Bethlehem PA. So they just need to trade bio lines.

The second is more interesting. At least on my end, in the races-race-results table, there are more than a few instances of a driver entering a particular raceId multiple times. Perhaps this is reflecting a legitimate reality and I just don't know enough about F1. I'm attaching an Excel spreadsheet that records my observations of this discrepancy. They occur overwhelmingly but not exclusively in the 1950s, and the Indy 500 races also seem to be over-represented. If this is an intentional way to record some dimension of F1, then I'm interested in what that is. I only use the csv files, so if nobody else is seeing these duplicates, then I suppose that's what I get for relying on csv files as a databasing solution!
[F1DB_race_entry_duplicates.xlsx](https://github.com/f1db/f1db/files/13943287/F1DB_race_entry_duplicates.xlsx)

Love the project and many thanks in advance!

**Comment by marceloverdijk** [comment]
Hi @mcnulty4960 ,

Good catch about the Michael Andretti and Michael Ammermuller swapped data.
I just fixed this by correcting the date of birth, place/country of birth and nationality for both drivers (see commits [11db7b6](https://github.com/f1db/f1db/commit/11db7b619ff701bce20b0684ebb07e14ab49fc4f) and [26b2843](https://github.com/f1db/f1db/commit/26b28431007551a5a242ff251bca3fc48e7de5c5)) and this will be available in the next relese.

For the second this might feel strange but is actually true. Especially in the early days of Formula 1 some drove for multiple teams in the same race. But I will verify your Excel later, as there could be of course some incorrect data in files in this repo. Thx again I will get back to you on this.

**Comment by mcnulty4960** [comment]
Gotcha! The Jim Clark double entry in raceId 130 is what caused me to first notice this, and I still find it flummoxing. In that race, for Jim, it's the same team listed twice. One of the entries is populated like normal, whereas the other has NAs in all of its fields except for the sharedCar field which is marked true (the more populated entry marks sharedCar as false). Thanks for your reply!

**Comment by marceloverdijk** [comment]
Yes, I can imagine at first sight this looks weird.
In these days drivers swapped cars when they had a problem with their "own" car.
For raceId, Jim Clark first drove the Lotus Climax with number 1. Later in the race he swapped with car number 2 which Mike Spence was driving.

Is it OK to close this issue?

**Comment by mcnulty4960** [comment]
Ah that does make sense then. Thanks for the explanation, and yes let's close this!
