### ISSUE TITLE
Mistakes in some race data (Car number and some missing results)

### ISSUE THREAD

**Issue by AntonioSchez32** [f1db/f1db#25]
I've found some mistakes. I wrote a script to fix them, but it would be great if you could include them in your database.

[FixScript.zip](https://github.com/f1db/f1db/files/14251991/FixScript.zip)

**Comment by AntonioSchez32** [comment]
Thanks a lot! I checked data in statsf1.com and formula1db.com.

**Comment by marceloverdijk** [comment]
Hi @AntonioSchez32,

First of all thanks for your contribution.

I've fixed many of the data issues in this [commit](https://github.com/f1db/f1db/commit/b76c6ff2dc3b79a5b8f4eaf7c21fa947e0a64cd8).

Some points I haven't done (yet) as I could not verify. Maybe you have other references for these points?


- [x] `UPDATE race_data SET driver_number=17 WHERE driver_id='olivier-grouillard' AND race_id=514 AND driver_number=14;`
- [x] `UPDATE race_data SET driver_number=10 WHERE driver_id='slim-borgudd' AND race_id=348 AND driver_number=9;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=351 AND driver_number=10;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=352 AND driver_number=10;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=353 AND driver_number=10;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=354 AND driver_number=10;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=355 AND driver_number=10;`
- [x] `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=356 AND driver_number=10;`

- [ ] `UPDATE race_data SET driver_number=10 WHERE driver_id='jan-lammers' AND race_id=331 AND driver_number=9;`

According to F1.com and Wikipedia (https://en.wikipedia.org/wiki/1980_Formula_One_season)
Jan lammers had driver number 9 during the South African GP.
Do you have other information or references?

- [x] `UPDATE race_data SET driver_number=10 WHERE driver_id='keke-rosberg' AND race_id=312 AND driver_number=32;`
- [x] `UPDATE race_data SET driver_number=10 WHERE driver_id='keke-rosberg' AND race_id=313 AND driver_number=32;`

- [ ] `UPDATE race_data SET driver_number=23 WHERE driver_id='lamberto-leoni' AND race_id=300 AND driver_number=22;`

Both F1.com and Wikipedia state driver number 22.
Also see https://www.racingsportscars.com/driver/archive/Lamberto-Leoni-I.html
Do you have other information or references?

- [x] `UPDATE race_data SET driver_number=27 WHERE driver_id='larry-perkins' AND race_id=276 AND driver_number=37;`
- [x] `UPDATE race_data SET driver_number=22 WHERE driver_id='chris-amon' AND race_id=248 AND driver_number=30;`
- [x] `UPDATE race_data SET driver_number=25 WHERE driver_id='mike-wilds' AND race_id=248 AND driver_number=22;`
- [x] `UPDATE race_data SET driver_number=44 WHERE driver_id='leo-kinnunen' AND race_id=240 AND driver_number=23;`
- [x] `UPDATE race_data SET driver_number=56 WHERE driver_id='denny-hulme' AND race_id=239 AND driver_number=6;`
- [x] `UPDATE race_data SET driver_number=24 WHERE driver_id='tim-schenken' AND race_id=220 AND driver_number=22;`
- [x] `UPDATE race_data SET driver_number=26 WHERE driver_id='chris-craft' AND race_id=207 AND driver_number=24;`
- [x] `UPDATE race_data SET driver_number=5 WHERE driver_id='clay-regazzoni' AND race_id=200 AND driver_number=3;`
- [x] `UPDATE race_data SET driver_number=21 WHERE driver_id='silvio-moser' AND race_id=164 AND driver_number=22;`
- [x] `UPDATE race_data SET driver_number=14 WHERE driver_id='jo-siffert' AND race_id=158 AND driver_number=6;`
- [x] `UPDATE race_data SET driver_number=28 WHERE driver_id='willy-mairesse' AND race_id=134 AND driver_number=29;`
- [x] `UPDATE race_data SET driver_number=25 WHERE driver_id='ronnie-bucknum' AND race_id=130 AND driver_number=28;`
- [x] `UPDATE race_data SET driver_number=32 WHERE driver_id='bob-anderson' AND race_id=125 AND driver_number=19;`
- [x] `UPDATE race_data SET driver_number=36 WHERE driver_id='mike-hailwood' AND race_id=125 AND driver_number=6;`
- [x] `UPDATE race_data SET driver_number=48 WHERE driver_id='tony-marsh' AND race_id=99 AND driver_number=25;`
- [x] `UPDATE race_data SET driver_number=60 WHERE driver_id='lorenzo-bandini' AND race_id=99 AND driver_number=62;`
- [x] `UPDATE race_data SET driver_number=46 WHERE driver_id='wolfgang-seidel' AND race_id=98 AND driver_number=40;`
- [x] `UPDATE race_data SET driver_number=32 WHERE driver_id='cliff-allison' AND race_id=86 AND driver_number=24;`
- [x] `UPDATE race_data SET driver_number=22 WHERE driver_id='wolfgang-von-trips' AND race_id=73 AND driver_number=24;`
- [x] `UPDATE race_data SET driver_number=24 WHERE driver_id='mike-hawthorn' AND race_id=73 AND driver_number=22;`
- [x] `UPDATE race_data SET driver_number=2 WHERE driver_id='giovanni-de-riu' AND race_id=40 AND driver_number=20;`
- [x] `UPDATE race_data SET driver_number=32 WHERE driver_id='jacky-ickx' AND race_id=208 AND driver_number=4;`

- [ ] `UPDATE race_data SET driver_id='jean-behra' WHERE driver_id='maurice-trintignant' AND race_id=14 AND driver_number=50 AND race_data."type"='RACE_RESULT';`

Interesting one... I want to keep the official outcome.

- [x] `DELETE FROM race_data WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=25;`
- [x] `UPDATE race_data SET position_display_order = 25 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=26;`
- [x] `UPDATE race_data SET position_display_order = 26 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=27;`
- [x] `UPDATE race_data SET position_display_order = 27 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=28;`
- [x] `INSERT INTO race_data
  (race_id, "type", position_display_order, position_number, position_text, driver_number, driver_id, constructor_id, engine_manufacturer_id, tyre_manufacturer_id, practice_time, practice_time_millis, practice_gap, practice_gap_millis, practice_interval, practice_interval_millis, practice_laps, qualifying_time, qualifying_time_millis, qualifying_q1, qualifying_q1_millis, qualifying_q2, qualifying_q2_millis, qualifying_q3, qualifying_q3_millis, qualifying_gap, qualifying_gap_millis, qualifying_interval, qualifying_interval_millis, qualifying_laps, starting_grid_position_grid_penalty, starting_grid_position_grid_penalty_positions, starting_grid_position_time, starting_grid_position_time_millis, race_shared_car, race_laps, race_time, race_time_millis, race_time_penalty, race_time_penalty_millis, race_gap, race_gap_millis, race_gap_laps, race_interval, race_interval_millis, race_reason_retired, race_points, race_grid_position_number, race_grid_position_text, race_positions_gained, race_pit_stops, race_fastest_lap, race_driver_of_the_day, race_grand_slam, fastest_lap_lap, fastest_lap_time, fastest_lap_time_millis, fastest_lap_gap, fastest_lap_gap_millis, fastest_lap_interval, fastest_lap_interval_millis, pit_stop_stop, pit_stop_lap, pit_stop_time, pit_stop_time_millis, driver_of_the_day_percentage)
  VALUES(551, 'RACE_RESULT', 27, NULL, 'DNF', '11', 'pedro-lamy', 'benetton', 'ford', 'goodyear', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Collision', NULL, 22, '22', NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);`
- [x] `INSERT INTO race_data
  (race_id, "type", position_display_order, position_number, position_text, driver_number, driver_id, constructor_id, engine_manufacturer_id, tyre_manufacturer_id, practice_time, practice_time_millis, practice_gap, practice_gap_millis, practice_interval, practice_interval_millis, practice_laps, qualifying_time, qualifying_time_millis, qualifying_q1, qualifying_q1_millis, qualifying_q2, qualifying_q2_millis, qualifying_q3, qualifying_q3_millis, qualifying_gap, qualifying_gap_millis, qualifying_interval, qualifying_interval_millis, qualifying_laps, starting_grid_position_grid_penalty, starting_grid_position_grid_penalty_positions, starting_grid_position_time, starting_grid_position_time_millis, race_shared_car, race_laps, race_time, race_time_millis, race_time_penalty, race_time_penalty_millis, race_gap, race_gap_millis, race_gap_laps, race_interval, race_interval_millis, race_reason_retired, race_points, race_grid_position_number, race_grid_position_text, race_positions_gained, race_pit_stops, race_fastest_lap, race_driver_of_the_day, race_grand_slam, fastest_lap_lap, fastest_lap_time, fastest_lap_time_millis, fastest_lap_gap, fastest_lap_gap_millis, fastest_lap_interval, fastest_lap_interval_millis, pit_stop_stop, pit_stop_lap, pit_stop_time, pit_stop_time_millis, driver_of_the_day_percentage)
  VALUES(551, 'RACE_RESULT', 28, NULL, 'DNF', '6', 'jj-lehto', 'lotus', 'mugen-honda', 'goodyear', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Collision', NULL, 5, '5', NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);`

- [ ] `UPDATE race_data
  SET driver_number=22, driver_id='francois-migault'
  WHERE race_id=255 AND "type"='RACE_RESULT' AND position_display_order=21;`

According to https://en.wikipedia.org/wiki/1975_Formula_One_season Francois Migault was no entrant for the 1975 Monaco GP.
Do you have other information or references?

**Comment by AntonioSchez32** [comment]
> Hi @AntonioSchez32,
> 
> First of all thanks for your contribution.
> 
> I've fixed many of the data issues in this [commit](https://github.com/f1db/f1db/commit/b76c6ff2dc3b79a5b8f4eaf7c21fa947e0a64cd8).
> 
> Some points I haven't done (yet) as I could not verify. Maybe you have other references for these points?
> 
> * [x]  `UPDATE race_data SET driver_number=17 WHERE driver_id='olivier-grouillard' AND race_id=514 AND driver_number=14;`
> * [x]  `UPDATE race_data SET driver_number=10 WHERE driver_id='slim-borgudd' AND race_id=348 AND driver_number=9;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=351 AND driver_number=10;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=352 AND driver_number=10;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=353 AND driver_number=10;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=354 AND driver_number=10;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=355 AND driver_number=10;`
> * [x]  `UPDATE race_data SET driver_number=9 WHERE driver_id='slim-borgudd' AND race_id=356 AND driver_number=10;`
> * [ ]  `UPDATE race_data SET driver_number=10 WHERE driver_id='jan-lammers' AND race_id=331 AND driver_number=9;`
> 
> According to F1.com and Wikipedia (https://en.wikipedia.org/wiki/1980_Formula_One_season) Jan lammers had driver number 9 during the South African GP. Do you have other information or references?
> 
> * [x]  `UPDATE race_data SET driver_number=10 WHERE driver_id='keke-rosberg' AND race_id=312 AND driver_number=32;`
> * [x]  `UPDATE race_data SET driver_number=10 WHERE driver_id='keke-rosberg' AND race_id=313 AND driver_number=32;`
> * [ ]  `UPDATE race_data SET driver_number=23 WHERE driver_id='lamberto-leoni' AND race_id=300 AND driver_number=22;`
> 
> Both F1.com and Wikipedia state driver number 22. Also see https://www.racingsportscars.com/driver/archive/Lamberto-Leoni-I.html Do you have other information or references?
> 
> * [x]  `UPDATE race_data SET driver_number=27 WHERE driver_id='larry-perkins' AND race_id=276 AND driver_number=37;`
> * [x]  `UPDATE race_data SET driver_number=22 WHERE driver_id='chris-amon' AND race_id=248 AND driver_number=30;`
> * [x]  `UPDATE race_data SET driver_number=25 WHERE driver_id='mike-wilds' AND race_id=248 AND driver_number=22;`
> * [x]  `UPDATE race_data SET driver_number=44 WHERE driver_id='leo-kinnunen' AND race_id=240 AND driver_number=23;`
> * [x]  `UPDATE race_data SET driver_number=56 WHERE driver_id='denny-hulme' AND race_id=239 AND driver_number=6;`
> * [x]  `UPDATE race_data SET driver_number=24 WHERE driver_id='tim-schenken' AND race_id=220 AND driver_number=22;`
> * [x]  `UPDATE race_data SET driver_number=26 WHERE driver_id='chris-craft' AND race_id=207 AND driver_number=24;`
> * [x]  `UPDATE race_data SET driver_number=5 WHERE driver_id='clay-regazzoni' AND race_id=200 AND driver_number=3;`
> * [x]  `UPDATE race_data SET driver_number=21 WHERE driver_id='silvio-moser' AND race_id=164 AND driver_number=22;`
> * [x]  `UPDATE race_data SET driver_number=14 WHERE driver_id='jo-siffert' AND race_id=158 AND driver_number=6;`
> * [x]  `UPDATE race_data SET driver_number=28 WHERE driver_id='willy-mairesse' AND race_id=134 AND driver_number=29;`
> * [x]  `UPDATE race_data SET driver_number=25 WHERE driver_id='ronnie-bucknum' AND race_id=130 AND driver_number=28;`
> * [x]  `UPDATE race_data SET driver_number=32 WHERE driver_id='bob-anderson' AND race_id=125 AND driver_number=19;`
> * [x]  `UPDATE race_data SET driver_number=36 WHERE driver_id='mike-hailwood' AND race_id=125 AND driver_number=6;`
> * [x]  `UPDATE race_data SET driver_number=48 WHERE driver_id='tony-marsh' AND race_id=99 AND driver_number=25;`
> * [x]  `UPDATE race_data SET driver_number=60 WHERE driver_id='lorenzo-bandini' AND race_id=99 AND driver_number=62;`
> * [x]  `UPDATE race_data SET driver_number=46 WHERE driver_id='wolfgang-seidel' AND race_id=98 AND driver_number=40;`
> * [x]  `UPDATE race_data SET driver_number=32 WHERE driver_id='cliff-allison' AND race_id=86 AND driver_number=24;`
> * [x]  `UPDATE race_data SET driver_number=22 WHERE driver_id='wolfgang-von-trips' AND race_id=73 AND driver_number=24;`
> * [x]  `UPDATE race_data SET driver_number=24 WHERE driver_id='mike-hawthorn' AND race_id=73 AND driver_number=22;`
> * [x]  `UPDATE race_data SET driver_number=2 WHERE driver_id='giovanni-de-riu' AND race_id=40 AND driver_number=20;`
> * [x]  `UPDATE race_data SET driver_number=32 WHERE driver_id='jacky-ickx' AND race_id=208 AND driver_number=4;`
> * [ ]  `UPDATE race_data SET driver_id='jean-behra' WHERE driver_id='maurice-trintignant' AND race_id=14 AND driver_number=50 AND race_data."type"='RACE_RESULT';`
> 
> Interesting one... I want to keep the official outcome.
> 
> * [x]  `DELETE FROM race_data WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=25;`
> * [x]  `UPDATE race_data SET position_display_order = 25 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=26;`
> * [x]  `UPDATE race_data SET position_display_order = 26 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=27;`
> * [x]  `UPDATE race_data SET position_display_order = 27 WHERE race_id=389 AND "type"='RACE_RESULT' AND position_display_order=28;`
> * [x]  `INSERT INTO race_data (race_id, "type", position_display_order, position_number, position_text, driver_number, driver_id, constructor_id, engine_manufacturer_id, tyre_manufacturer_id, practice_time, practice_time_millis, practice_gap, practice_gap_millis, practice_interval, practice_interval_millis, practice_laps, qualifying_time, qualifying_time_millis, qualifying_q1, qualifying_q1_millis, qualifying_q2, qualifying_q2_millis, qualifying_q3, qualifying_q3_millis, qualifying_gap, qualifying_gap_millis, qualifying_interval, qualifying_interval_millis, qualifying_laps, starting_grid_position_grid_penalty, starting_grid_position_grid_penalty_positions, starting_grid_position_time, starting_grid_position_time_millis, race_shared_car, race_laps, race_time, race_time_millis, race_time_penalty, race_time_penalty_millis, race_gap, race_gap_millis, race_gap_laps, race_interval, race_interval_millis, race_reason_retired, race_points, race_grid_position_number, race_grid_position_text, race_positions_gained, race_pit_stops, race_fastest_lap, race_driver_of_the_day, race_grand_slam, fastest_lap_lap, fastest_lap_time, fastest_lap_time_millis, fastest_lap_gap, fastest_lap_gap_millis, fastest_lap_interval, fastest_lap_interval_millis, pit_stop_stop, pit_stop_lap, pit_stop_time, pit_stop_time_millis, driver_of_the_day_percentage) VALUES(551, 'RACE_RESULT', 27, NULL, 'DNF', '11', 'pedro-lamy', 'benetton', 'ford', 'goodyear', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Collision', NULL, 22, '22', NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);`
> * [x]  `INSERT INTO race_data (race_id, "type", position_display_order, position_number, position_text, driver_number, driver_id, constructor_id, engine_manufacturer_id, tyre_manufacturer_id, practice_time, practice_time_millis, practice_gap, practice_gap_millis, practice_interval, practice_interval_millis, practice_laps, qualifying_time, qualifying_time_millis, qualifying_q1, qualifying_q1_millis, qualifying_q2, qualifying_q2_millis, qualifying_q3, qualifying_q3_millis, qualifying_gap, qualifying_gap_millis, qualifying_interval, qualifying_interval_millis, qualifying_laps, starting_grid_position_grid_penalty, starting_grid_position_grid_penalty_positions, starting_grid_position_time, starting_grid_position_time_millis, race_shared_car, race_laps, race_time, race_time_millis, race_time_penalty, race_time_penalty_millis, race_gap, race_gap_millis, race_gap_laps, race_interval, race_interval_millis, race_reason_retired, race_points, race_grid_position_number, race_grid_position_text, race_positions_gained, race_pit_stops, race_fastest_lap, race_driver_of_the_day, race_grand_slam, fastest_lap_lap, fastest_lap_time, fastest_lap_time_millis, fastest_lap_gap, fastest_lap_gap_millis, fastest_lap_interval, fastest_lap_interval_millis, pit_stop_stop, pit_stop_lap, pit_stop_time, pit_stop_time_millis, driver_of_the_day_percentage) VALUES(551, 'RACE_RESULT', 28, NULL, 'DNF', '6', 'jj-lehto', 'lotus', 'mugen-honda', 'goodyear', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Collision', NULL, 5, '5', NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);`
> * [ ]  `UPDATE race_data SET driver_number=22, driver_id='francois-migault' WHERE race_id=255 AND "type"='RACE_RESULT' AND position_display_order=21;`
> 
> According to https://en.wikipedia.org/wiki/1975_Formula_One_season Francois Migault was no entrant for the 1975 Monaco GP. Do you have other information or references?

* [ ]  `UPDATE race_data SET driver_number=10 WHERE driver_id='jan-lammers' AND race_id=331 AND driver_number=9;`

I agree with you. I was using this source https://www.formula1db.com/races/1980-south-african-grand-prix/info, but apparently there were two cars with number 9 https://www.statsf1.com/en/1980/afrique-du-sud/engages.aspx

* [ ]  `UPDATE race_data SET driver_number=23 WHERE driver_id='lamberto-leoni' AND race_id=300 AND driver_number=22;`

Again, the same case. I was using this source https://www.formula1db.com/races/1978-south-african-grand-prix/info, but it seems you are right https://www.statsf1.com/en/1978/afrique-du-sud/classement.aspx

* [ ]  `UPDATE race_data SET driver_id='jean-behra' WHERE driver_id='maurice-trintignant' AND race_id=14 AND driver_number=50 AND race_data."type"='RACE_RESULT';`

This one I have re-verify and is correct https://www.statsf1.com/en/1951/italie/classement.aspx. It seems Maurice Trintignant felt unwell and was replaced by Jean Behra before the race although he was the one who qualified https://www.statsf1.com/en/1951/italie/qualification.aspx. Definitely, this doesn't happen nowadays.

* [ ]  `UPDATE race_data SET driver_number=22, driver_id='francois-migault' WHERE race_id=255 AND "type"='RACE_RESULT' AND position_display_order=21;`

It seems he withdrew from the race https://www.statsf1.com/en/1975/monaco/classement.aspx. Please re-check the results of this race because there may be another mistakes and it may be tricky.

**Comment by marceloverdijk** [comment]
Thanks!, I will re-evaluate the open points this evening.

**Comment by marceloverdijk** [comment]
> [ ] `UPDATE race_data SET driver_number=22, driver_id='francois-migault' WHERE race_id=255 AND "type"='RACE_RESULT' AND position_display_order=21;`
> 
> It seems he withdrew from the race https://www.statsf1.com/en/1975/monaco/classement.aspx. Please re-check the results of this race because there may be another mistakes and it may be tricky.

What I can find [here](https://en.wikipedia.org/wiki/1975_Formula_One_season) and [here](https://en.wikipedia.org/wiki/1975_Monaco_Grand_Prix) both Migault and Pescorolo never were official entries for the 1975 Monaco GP; probably because there cars were not available as stated here: https://www.statsf1.com/en/1975/monaco/classement.aspx
I've seen such a things in other (old) races and back then I decided to only include drivers that officially entered the race.
So probably better to leave them out; as it is also unclear for which entrant they would have participated.

**Comment by AntonioSchez32** [comment]
> > [ ] `UPDATE race_data SET driver_number=22, driver_id='francois-migault' WHERE race_id=255 AND "type"='RACE_RESULT' AND position_display_order=21;`
> > It seems he withdrew from the race https://www.statsf1.com/en/1975/monaco/classement.aspx. Please re-check the results of this race because there may be another mistakes and it may be tricky.
> 
> What I can find [here](https://en.wikipedia.org/wiki/1975_Formula_One_season) and [here](https://en.wikipedia.org/wiki/1975_Monaco_Grand_Prix) both Migault and Pescorolo never were official entries for the 1975 Monaco GP; probably because there cars were not available as stated here: https://www.statsf1.com/en/1975/monaco/classement.aspx I've seen such a things in other (old) races and back then I decided to only include drivers that officially entered the race. So probably better to leave them out; as it is also unclear for which entrant they would have participated.

OK, but please check the rest of the results of the 1975 Monaco GP. I think Graham Hill appears two times.

**Comment by marceloverdijk** [comment]
> OK, but please check the rest of the results of the 1975 Monaco GP. I think Graham Hill appears twice.

I now see what you mean. I removed the Graham Hill Lola-Ford entry for that the 1975 Monaco GP via https://github.com/f1db/f1db/commit/2421db44aaa44bf7835f59be4a57cd0f9871eb41 and https://github.com/f1db/f1db/commit/a4426465200a8df67c501af94e13c513c69a1c41

**Comment by marceloverdijk** [comment]
> [ ] `UPDATE race_data SET driver_id='jean-behra' WHERE driver_id='maurice-trintignant' AND race_id=14 AND driver_number=50 AND race_data."type"='RACE_RESULT';`
> 
> This one I have re-verify and is correct https://www.statsf1.com/en/1951/italie/classement.aspx. It seems Maurice Trintignant felt unwell and was replaced by Jean Behra before the race although he was the one who qualified https://www.statsf1.com/en/1951/italie/qualification.aspx. Definitely, this doesn't happen nowadays.

And for the interesting one... 
As [Wikipedia](https://en.wikipedia.org/wiki/1951_Italian_Grand_Prix) states: 
> Behra secretly replaced the unwell Trintignant for the race. Team principal [Amédée Gordini](https://en.wikipedia.org/wiki/Am%C3%A9d%C3%A9e_Gordini) did not inform the race organizers about the switch as it would have cut the team's starting fee. Behra even wore his compatriot's helmet to disguise the switch.

That's why in the official results Maurice Trintignant is classified to have raced.
As many other sources use as well:
- https://www.formula1.com/en/results.html/1951/races/107/italy/race-result.html
- https://en.wikipedia.org/wiki/1951_Italian_Grand_Prix
- http://en.espn.co.uk/f1/motorsport/race/1402.html
So I prefer to keep it as it is.

**Comment by marceloverdijk** [comment]
I think we processed them all. Are you missing something or is ok now to close the issue?

**Comment by marceloverdijk** [comment]
PS: I just released [v2024.0.0.beta3](https://github.com/f1db/f1db/releases/tag/v2024.0.0.beta3) which includes the changes mentioned in this issue thread.

**Comment by AntonioSchez32** [comment]
If you consider that results are OK, you can close this.

**Comment by AntonioSchez32** [comment]
I'm sorry to bother you again. But I think you should check these results.
It turns out I'm joining race, qualifying and starting grid queries, and it seems the car number is wrong for these results in qualifying and starting grid. For example, Fangio in that race raced with two cars, but he qualified with car number 4 (https://www.statsf1.com/es/1953/belgique/engages.aspx)

![image](https://github.com/f1db/f1db/assets/72667525/2662e658-a6f5-459f-90db-fa870652a045)


Please check these too. It seems these results are from qualifying and don't have a match in the race. I understand if you don't want to include them in the race because they didn't participate but the first result in that list (Bernie Ecclestone) it seems wrong since he neither participated nor qualified in that race (https://www.statsf1.com/es/1958/grande-bretagne/engages.aspx).
![image](https://github.com/f1db/f1db/assets/72667525/9f533804-0463-4941-b2d0-4bea7a54504c)


And I have a final question. In 1984 Tyrrell was disqualified, why you haven't kept the starting grid and qualifying results?
Thank you so much!

**Comment by marceloverdijk** [comment]
No worries at all @AntonioSchez32 , I will have a look at in the weekend.

**Comment by marceloverdijk** [comment]
Thx again for bringing this up @AntonioSchez32 , I have corrected the data as you suggested.

For the Tyrrell 1984 data I indeed scrapped all the results. I agree this is debatable but for this I followed the official data from F1.com: https://www.formula1.com/en/results.html/1984/races/466/brazil/race-result.html
