### ISSUE TITLE
2014 Bahrain GP in f1db-races table

### ISSUE THREAD

**Issue by mcnulty4960** [f1db/f1db#33]
Hello! The 2014 Bahrain GP was on April 6th, 2014, or 2014-04-06. In the f1db-races table, the date appears to have been accidentally flipped as it was typed, and shows 2014-06-04 (June 4th). So it can be simply flipped back. Love the project, thanks for maintaining it!

**Comment by marceloverdijk** [comment]
Thx @mcnulty4960 for the nice words and noticing this!
