### ISSUE TITLE
Postgres script being generated with errors

### ISSUE THREAD

**Issue by ivanyort** [f1db/f1db#42]
To reproduce

git pull origin main
./gradlew clean dist assemble

After the successful assemble, there is a new file ./build/data/sql/f1db-sql-postgresql.sql

The "create view" statements have syntax errors, example below (and error in bold). If we remove the additional **'create view "xxx" as'**, the script runs without errors.

Thanks.

CREATE VIEW "pre_qualifying_result"(
  "race_id",
  "position_display_order",
  "position_number",
  "position_text",
  "driver_number",
  "driver_id",
  "constructor_id",
  "engine_manufacturer_id",
  "tyre_manufacturer_id",
  "time",
  "time_millis",
  "gap",
  "gap_millis",
  "interval",
  "interval_millis",
  "laps"
)
AS
    **create view "pre_qualifying_result" as** SELECT
    "race_data"."race_id",
    "race_data"."position_display_order",
    "race_data"."position_number",
    "race_data"."position_text",
    "race_data"."driver_number",
    "race_data"."driver_id",
    "race_data"."constructor_id",
    "race_data"."engine_manufacturer_id",
    "race_data"."tyre_manufacturer_id",
    "race_data"."qualifying_time" AS "time",
    "race_data"."qualifying_time_millis" AS "time_millis",
    "race_data"."qualifying_gap" AS "gap",
    "race_data"."qualifying_gap_millis" AS "gap_millis",
    "race_data"."qualifying_interval" AS "interval",
    "race_data"."qualifying_interval_millis" AS "interval_millis",
    "race_data"."qualifying_laps" AS "laps"
FROM "PUBLIC"."race_data"
WHERE "race_data"."type" = 'PRE_QUALIFYING_RESULT'
;

**Comment by marceloverdijk** [comment]
Thanks for reporting this @ivanyort , I will have a look asap.

**Comment by marceloverdijk** [comment]
I'm releasing a `v2024.17.1` shortly which should fix this.
Thanks again for reporting this!

**Comment by ivanyort** [comment]
Thank you for the awesome project

Thanks!
