### ISSUE TITLE
Generate CSV from the database

### ISSUE THREAD

**Issue by enrique-lozano** [f1db/f1db#7]
It would be great if you could have the files in CSV format, a very light format and easy to analyze by data analysis frameworks.

An example of how these files could be structured would be something like this:
https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020

(note that at this link we have a lap_times file, something that is currently missing from this project and would be nice to add as well)

**Comment by marceloverdijk** [comment]
I will try to get this for the `2023.0.0.alpha1` version and as I already experimented with it in the past it should not be a big deal.

For the lap times, could you please create a separate issue?

**Comment by marceloverdijk** [comment]
CSV format is now available since v2023.0.0.alpha2.

**Comment by marceloverdijk** [comment]
Hi @enrique-lozano `v2023.0.0.alpha2` is now available with a csv export.
Your feedback is appreciated and let me know if encounter something unexpected.
